name: Test
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  Test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.1.0

      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies 
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - run: python --version

      - name: Install Python dependencies form requirements.txt
        run: pip install -r requirements.txt

      - name: Python Linters
        uses: wearerequired/lint-action@v2.1.0
        with:
          black: true
          flake8: true

      - run: dig ns dnslabs.nl
      - run: dig ns dnslabs.nl @8.8.8.8
      - run: dig ns dnslabs.nl @2001:4860:4860::8888 # Google Public DNS IPv6 resolver
      - run: dig ns dnslabs.nl @2001:4860:4860::6464 # Google Public DNS64
      - run: dig ns dnslabs.nl @1.1.1.1
      - name: Run Python
        run: python test.py
