name: Test
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  Test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install black flake8 dnspython

      - name: Python Linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true

      - run: dig ns dnslabs.nl
      - run: dig ns dnslabs.nl @8.8.8.8
      - run: dig ns dnslabs.nl @1.1.1.1
      - name: Run Python
        run: python test.py
